name: unicorn_flutter
description: "命を救う次世代ロボットシステム「Unicorn」"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_gen_runner: ^5.7.0
  go_router: ^14.2.8
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  fluttertoast: ^8.2.8
  build_runner: ^2.4.9
  go_router_builder: ^2.7.1
  percent_indicator: ^4.2.3
  cached_network_image: ^3.4.0
  loading_animation_widget: ^1.1.0+3
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  assets:
    exclude:
      - .env.develop
      - .env.release

flutter:
  uses-material-design: true

  assets:
    - .env.develop
    - .env.release
    - assets/images/
    - assets/images/icons/
    

  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
