name: unicorn_flutter
description: "命を救う次世代ロボットシステム「Unicorn」"
publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_gen_runner: ^5.7.0
  go_router: ^14.2.8
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  fluttertoast: ^8.2.8
  build_runner: ^2.4.9
  go_router_builder: ^2.7.1
  percent_indicator: ^4.2.3
  cached_network_image: ^3.4.0
  loading_animation_widget: ^1.1.0+3
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0
  firebase_core: ^3.4.0
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.2.0
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  contacts_service: ^0.6.3
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  dots_indicator: ^3.0.0
  google_maps_flutter: ^2.2.8
  flutter_config: ^2.0.2
  firebase_messaging: ^15.1.0
  uuid: ^4.5.1
  firebase_storage: ^12.2.0
  image: ^4.3.0
  agora_rtc_engine: ^6.3.2
  stomp_dart_client: ^2.0.0
  in_app_review: ^2.0.9
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  avatar_glow: ^3.0.1
  table_calendar: ^3.1.2
  audioplayers: ^6.1.0
  tutorial_coach_mark: ^1.2.12
  cloud_firestore: ^5.4.0
  collection: ^1.18.0
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  assets:
    exclude:
      - .env.develop
      - .env.release

flutter_icons:
  ios: true
  image_path: "assets/images/launcher/unicorn_app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env.develop
    - .env.release
    - assets/images/
    - assets/images/icons/
    - assets/images/bottom_nav_bar/
    - assets/sounds/

  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
